<img style="float: left; margin: 30px 15px 15px 15px;" src="https://pngimage.net/wp-content/uploads/2018/06/logo-iteso-png-5.png" width="300" height="500" /> 
    
    
### <font color='navy'> Simulación de procesos financieros. 

**Nombres:** Ricardo Rodriguez, Doris Gomez, Carlos Ruiz.

**Fecha:** 18 de septiembre del 2020.

**Expediente** : IF722544, IF707135, IF713897.
**Profesor:** Oscar David Jaramillo Zuluaga.

# Tarea 2b: Clase 5


# Github en el cual realizamos el trabajo

https://github.com/D0r1s/Tarea2b_DGomez_RRodriguez_CRuiz/blob/master/Tarea2b_DGomez_RRodriguez_CRuiz.ipynbk


### Tarea 2: Segunda entrega(Usando notebook de jupyter)**
Usando compresión de listas o funciones map o según lo indique, resolver los siguientes ejercicios:

## Ejercicio 1:
1. Imagine una rutina contable utilizada en una librería. Funciona en una lista con sublistas, que se ven así:
![imagen.png](attachment:imagen.png)
Escriba un programa en Python, que devuelve una lista con tuplas de tamaño 2. Cada tupla consiste en el número de pedido y el costo total del pedido. El producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €. 
Escribe un programa Python usando unicamente las funciones **lambda y map**.

`orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]`

In [4]:
### Respuestas planteadas en el ejercicio:
#solucion Ricks
orders = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
minimum= 100
totals = list(map(lambda x: x if x[1] >= minimum else (x[0], x[1] + 10), map(lambda x: (x[0],x[2] * x[3]), orders)))
print(totals)

[('34587', 163.8), ('98762', 284.0), ('77226', 108.85000000000001), ('88112', 84.97)]


### Respuesta planteada en el ejercicio:


## Ejercicio 2:
2. La misma librería, pero esta vez trabajamos en una lista diferente. Las sublistas de nuestras listas se ven así: 
[número de orden, (número de artículo, cantidad, precio por unidad), ... (número de artículo, cantidad, precio por unidad)] 

`orders = [[1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
	       [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
	       [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]`

Escriba un programa que devuelva una lista de dos tuplas que tengan la información de (número de pedido, cantidad total de pedido). Utilice la función `Reduce`. Recuerde el precio del pedido del producto debe aumentarse en 10€ si el valor de la orden es inferior a 100,00 €.

In [5]:
### Respuestas planteadas en el ejercicio:
#solucion Ricks
from functools import reduce
orders = [ [1, ("5464", 4, 9.99), ("8274",18,12.99), ("9744", 9, 44.95)], 
           [2, ("5464", 9, 9.99), ("9744", 9, 44.95)],
           [3, ("5464", 9, 9.99), ("88112", 11, 24.99)],
           [4, ("8732", 7, 11.99), ("7733",11,18.99), ("88112", 5, 39.95)] ]
minimum_needed = 100
totals = list(map(lambda x: [x[0]] + list(map(lambda y: y[1]*y[2], x[1:])), orders))
totals = list(map(lambda x: [x[0]] + [reduce(lambda a,b: a + b, x[1:])], totals))
totals = list(map(lambda x: x if x[1] >= minimum_needed else (x[0], x[1] + 10), totals))

print (totals)

[[1, 678.3299999999999], [2, 494.46000000000004], [3, 364.79999999999995], [4, 492.57]]


### Respuesta planteada en el ejercicio:


## Ejercicio 3:

3. Resolver los anteriores ejercicios usando pandas (DataFrame)

In [8]:
### Respuestas planteadas en el ejercicio:
#solucion Ricky
import pandas as pd
orders1 = [ ["34587", "Learning Python, Mark Lutz", 4, 40.95], 
           ["98762", "Programming Python, Mark Lutz", 5, 56.80], 
           ["77226", "Head First Python, Paul Barry", 3,32.95],
           ["88112", "Einführung in Python3, Bernd Klein", 3, 24.99]]
orders2= orders1
s1,s2 =pd.DataFrame(orders1),pd.DataFrame(orders2)


additional = lambda k: k if k>= 100 else k+10
X = s1.iloc[:,2]* s1.iloc[:,3]


s1['Answer']  = X.apply(additional)
print(s1)

       0                                   1  2      3  Answer
0  34587          Learning Python, Mark Lutz  4  40.95  163.80
1  98762       Programming Python, Mark Lutz  5  56.80  284.00
2  77226       Head First Python, Paul Barry  3  32.95  108.85
3  88112  Einführung in Python3, Bernd Klein  3  24.99   84.97


### Respuesta planteada en el ejercicio:


## Ejercicio 4:
4. Use filter to eliminate all words that are shorter than 4 letters from a list of words
`list='the notion of a lambda function goes all the way back to the origin of computer science'`

In [10]:
### Respuestas planteadas en el ejercicio:
#solucion Ricks
list1="the notion of a lambda function goes all the way back to the origin of computer science"
words=list1.split()

result= list(filter(lambda p : len(p) < 4, words ))
print(result)


['the', 'of', 'a', 'all', 'the', 'way', 'to', 'the', 'of']


### Respuesta planteada en el ejercicio:


## Ejercicio 5:
5. Use filter to determine the percentage of Fahrenheit temperatures in a list are within the range 32 to 80

In [17]:
### Respuestas planteadas en el ejercicio:
import numpy as np
np.random.seed(55555)
farenheit = np.random.uniform(25,110,30)
print(farenheit)

[ 35.97387961  99.13294268  92.6178302   99.69549478  63.21119535
  73.90387697  95.50028838  99.21476553  36.98251238 101.45813729
 100.5917418   89.38159435  89.52156589  83.8084752   28.37990868
  68.75395211  45.86132067  36.58307493  56.32208365  33.96219302
  45.29071318  74.86289938  66.51091383  88.19316186  94.26635864
  46.83131624 109.60744472 109.68427993  44.55796499  92.84146259]


In [20]:
#solucion Ricks
filtro = list(filter(lambda t: (32  < t  < 80), farenheit))
filtro


[35.97387961379455,
 63.211195349983264,
 73.90387696517755,
 36.982512376595906,
 68.75395211338406,
 45.86132066984196,
 36.58307493022292,
 56.322083650154724,
 33.9621930206693,
 45.29071317816652,
 74.86289938282341,
 66.51091382521807,
 46.831316244170544,
 44.55796498523391]

### Respuesta planteada en el ejercicio:
'''''''''''''''''''''''''''''''''''''''''

## Ejercicio 6:
6. Use reduce to find the lower left corner (minimum x and minimum y value) for a list of point locations
> **Hint**: Explore the command `np.minimum.reduce` [link](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ufunc.reduce.html)

In [21]:
### Respuestas planteadas en el ejercicio:
#solucion Ricks
np.random.seed(55555)
xy_minimum = np.random.randint(0,50,[10,3])
print(xy_minimum)

[[17 43 33]
 [39 22 37]
 [33 49 37]
 [36 46 28]
 [11 37 25]
 [14  2 10]
 [16 37 12]
 [39 37 35]
 [21  2  1]
 [43 22 43]]


### Respuesta planteada en el ejercicio:
'''''''''''''''''''''''''''''''''''''''''